# Introducción a Numpy

In [2]:
import numpy as np

In [5]:
np.array([10, 20, 24, 15 ,50])

array([10, 20, 24, 15, 50])

In [17]:
a = np.array([10, 15, 20, 4, 30, 32, 31, 60, 4, 18, 72])

In [11]:
a[4]


30

In [19]:
a[3:]

array([ 4, 30, 32, 31, 60,  4, 18, 72])

In [15]:
a[3:7]


array([ 4, 30, 32, 31])

In [20]:
# desde la posicion 1 cada 4 elementos
a[1::4]

array([15, 32, 18])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
ones = np.ones((6))
ones


array([1., 1., 1., 1., 1., 1.])

In [39]:
type(ones)


numpy.ndarray

In [40]:
type(ones[3])

numpy.float64

In [43]:
# valor inicial, valor final , numero de elementos
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [45]:
b = np.array([['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [48]:
# numero de dimensiones
b.ndim

2

In [50]:
c = [12,3, 10 , 40, 2]

In [51]:
np.sort(c)

array([ 2,  3, 10, 12, 40])

In [53]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]

usuarios = np.array(datos, dtype=cabeceras)
usuarios

array([(b'Juan', 10), (b'Maria', 70), (b'Javier', 42), (b'Samuel', 15)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [54]:
np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [55]:
# total de valores
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
# valor inicial , valor final
np.arange(5,31)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
# valor inicial, valor final , incrementacion
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [64]:
# dimensiones, valor
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [65]:
# genera una diagonal con los valores del arreglo
np.diag([0, 3, 9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

# reto

Crear un arreglo de 3 dimensiones y ordendarlo por edad , nombre y pais

In [3]:
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S10')]
datos = [('Juan', 10, 'Colombia'), ('Maria', 70, 'Venezuela'), ('Javier', 42, 'Brazil'), ('Samuel', 15, 'Canada')]


In [4]:
usuarios = np.array(datos, dtype=cabeceras)
usuarios


array([(b'Juan', 10, b'Colombia'), (b'Maria', 70, b'Venezuela'),
       (b'Javier', 42, b'Brazil'), (b'Samuel', 15, b'Canada')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])

In [9]:
np.sort(usuarios,order='edad')


array([(b'Juan', 10, b'Colombia'), (b'Samuel', 15, b'Canada'),
       (b'Javier', 42, b'Brazil'), (b'Maria', 70, b'Venezuela')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])

In [11]:
np.sort(usuarios, order='nombre')


array([(b'Javier', 42, b'Brazil'), (b'Juan', 10, b'Colombia'),
       (b'Maria', 70, b'Venezuela'), (b'Samuel', 15, b'Canada')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])

In [12]:
np.sort(usuarios, order='pais')


array([(b'Javier', 42, b'Brazil'), (b'Samuel', 15, b'Canada'),
       (b'Juan', 10, b'Colombia'), (b'Maria', 70, b'Venezuela')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])